# Use RestClient by Huachao Mao - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = https://api.todoist.com/rest/v1
@token = 02982bae6154c10ed83c8238775aba4bf288aa7e


### get projects
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}


### get sections
@projectId = 2261883393
GET {{baseUrl}}/sections?project_id={{projectId}}
Authorization: Bearer {{token}}

### get tasks
GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}

### get comments
@taskId = 4700366412
GET {{baseUrl}}/comments?task_id={{taskId}}
Authorization: Bearer {{token}}
